// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCK3_nRQrTiW_Qu1tAVz4k7X6V1R18f1tw',
    appId: '1:858974112994:web:325cf36c894f1c87e062bb',
    messagingSenderId: '858974112994',
    projectId: 'tadrebk-website',
    authDomain: 'tadrebk-website.firebaseapp.com',
    storageBucket: 'tadrebk-website.appspot.com',
    measurementId: 'G-V3NMQCCF7K',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAoXe_1BqmtpUlRxuvfXuY9hC0qXfl3Txg',
    appId: '1:858974112994:android:cc841953e5305269e062bb',
    messagingSenderId: '858974112994',
    projectId: 'tadrebk-website',
    storageBucket: 'tadrebk-website.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD2Tg4xYsicZk3QoAzZoNGFH_7MBKVc7xU',
    appId: '1:858974112994:ios:85e8addc4dca4ac2e062bb',
    messagingSenderId: '858974112994',
    projectId: 'tadrebk-website',
    storageBucket: 'tadrebk-website.appspot.com',
    iosBundleId: 'com.example.flutterWeb',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD2Tg4xYsicZk3QoAzZoNGFH_7MBKVc7xU',
    appId: '1:858974112994:ios:14c5c008265153f9e062bb',
    messagingSenderId: '858974112994',
    projectId: 'tadrebk-website',
    storageBucket: 'tadrebk-website.appspot.com',
    iosBundleId: 'com.example.flutterWeb.RunnerTests',
  );
}
